### ISSUE TITLE
Missing libraries..

### ISSUE THREAD

**Issue by coquizen** [josuegaleas/JayKey2#1]
Which version of Kicad was used to generate this github? I am running `Version: (5.1.0-1407-gc624ee9cf), release build` and have installed the standard libraries. I also loaded the git submodules. But get the following error: 
![Kicad](https://user-images.githubusercontent.com/16412897/62406414-92cba280-b579-11e9-8cf8-1122bc1a573c.png)

**Comment by josuegaleas** [comment]
Oh this project has been stalled for a while now, it was made in 4.7. I'll get back to this project eventually. However, [JayKey1](https://github.com/josuegaleas/JayKey1) has been moved on to 5.0 and *should* open fine on 5.1. Hope this helps!

Edit: JayKey1, now called [JayK](https://github.com/josuegaleas/JayK), has been opened on 5.1 and known to work.

**Comment by josuegaleas** [comment]
I've opened the project on 5.1 now, and everything seems to be okay. Some symbols have changed but there shouldn't be any issues with missing footprints or libraries. However, the project is still a WIP, so some things may still be incorrect or incomplete.
